### ISSUE TITLE
Export TreeNode

### ISSUE THREAD

**Issue by flannelhead** [giogadi/kdt#3]
Would you mind exporting `TreeNode` from `Data.KdMap.Static`? It already derives `Generic`, and I would like to derive [`Serialize`](https://hackage.haskell.org/package/cereal-0.5.1.0/docs/Data-Serialize.html) to be able to save the tree in a binary form.

**Comment by giogadi** [comment]
Sure, I'll take care of it! Thanks for the heads-up.
