### ISSUE TITLE
Unexpected super-linear peformance

### ISSUE THREAD

**Issue by nstepp** [giogadi/kdt#6]
Hi, hopefully I am doing something wrong, but this performance surprised me.

I have point value tuples like:

```haskell
ghci> :t pvs
pvs :: [([Double], [(Int, Int)])]
```

that I use to build a `KdMap Double [Double] [(Int, Int)]` with something like

```haskell
kdt = KD.build id pvs
```

I noticed that using the resulting map was very slow, so I looked at how it scaled with number of elements in `pvs`:

```haskell
ghci> timekd n = do
ghci|   let kdt = KD.build (id) (take n pvs)
ghci|   start <- getCPUTime
ghci|   let l = length (KD.keys kdt)
ghci|   print l
ghci|   end <- getCPUTime
ghci|   print (end-start)
ghci|
ghci> mapM_ timekd [10,100,1000,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000]
10
104864000
100
840833000
1000
39424662000
5000
756960855000
10000
3012117673000
15000
7099718345000
20000
12695376600000
25000
20399871294000
30000
29515137611000
35000
40549988079000
40000
54849309725000
45000
69484019547000
50000
88674743895000
```

As you can see, the results are quadratic (and quite slow) in number of points. I'm assuming, and it says in the docs, that this should be linear.

![kdtimes2d](https://user-images.githubusercontent.com/47257699/216177595-ed4075af-4d0b-4e9a-81fd-f244342ea864.png)

Any ideas or explanations?

I am using `kdt-0.2.5` with `ghc-9.2.5` and `cabal-3.6.2.0`.

**Comment by giogadi** [comment]
I haven't worked with this library or Haskell in quite a while, so I may be misremembering some things. That said, thank you for the helpful analysis! Here are some of my thoughts:

1. It looks like you're running your timer only on the KD.keys function - looking at the documentation, you are correct that this is listed as a O(n) operation. However, Haskell is lazily evaluated, so it's _possible_ (I'm not certain) that, when you call KD.keys, you are _also_ evaluating "KD.build" at that time. The documentation lists the complexity of KD.build as O(n*log(n)), which is slower than linear. Honestly, I'm not sure whether I can look at that graph and say "yup that's definitely O(nlog(n))" or "that's definitely n^2". But the lazy evaluation would definitely at least explain why you're seeing slower-than-linear performance here.

2. Building the k-d tree does look slow, I agree. I did my best at the time (years ago) to optimize performance, but I'm no expert in Haskell; all I could say is that it was way faster than the existing Haskell k-d tree implementations at the time. However, k-d tree as an algorithm is not really about having the fastest build time; the intent is to be fast to query. You are expected to spend the time on building the tree just once, and then get that cost back by making many fast queries on the structure afterward. This doesn't excuse slow performance on the build! Just giving some context on expected usage.

**Comment by nstepp** [comment]
Thanks for the super fast reply! You are probably right about the lazy evaluation. I had previously observed that running `size` on the tree was fast, and I had assumed that would force evaluation of the build, but perhaps there's a shortcut for size that was leaving evaluations to be done.

I can tinker with that to see if I can differentiate the two, but I do think you are right about measuring build time. Thanks again.
